services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - ./data:/data
  app:
    build:
      context: .
    ports:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app